apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo5
spec:
  selector:
    matchLabels:
      app: yolo5
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: yolo5
    spec:
      containers:
      - name: yolo5
        image: public.ecr.aws/n5h8m9x0/yolo5-public-ex
        ports:
        - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: yolo5-service
spec:
  selector:
    app: yolo5
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081